#!/usr/bin/env python

'''
amcat: list all automounts stored in Active Directory formatted
       as plain text.
Part of ampush. https://github.com/sfu-rcg/ampush

Blame warren@sfu.ca.
'''

from amlib import ad_op, utils
from amlib import ad_map as adm

import argparse

p = argparse.ArgumentParser(
    prog='amcat',
    description="List Active Directory Automounts",
)

p.add_argument('maps',
               nargs='?',
               help="List one or more automount maps stored " +
                     "in Active Directory. No args == list all maps.")


def main():
    args = vars(p.parse_args())

    if args['maps'] is None:
        ad_maps = adm.get_names()
    else:
        ad_maps = args['maps']

    for map_name in ad_maps:
        print("\n### AD:" + map_name)
        d_map = adm.parse(map_name)
        l_map = utils.map_to_text(in_d=d_map, map_name=map_name)
        print('\n'.join(l_map))
    return

if __name__ == "__main__":
    main()
