#!/usr/bin/env python

'''
dump_admaps: display the contents of all flat file automount maps 
             in Python dict format.
Part of ampush. https://github.com/sfu-rcg/ampush

Blame warren@sfu.ca.
Copyright (C) 2016 Research Computing Group, Simon Fraser University.
'''

import sys
from amlib import conf, log, ad_op, utils, sync
from amlib import ad_map as adm
from pprint import pprint


def main():
    ad_maps = adm.get_names()
    print("Found AD maps ")
    print(ad_maps)

    for x in ad_maps:
        print("\n### AD:"+x)
        d_map = adm.parse(x)
        pprint(d_map)
    return

if __name__ == "__main__":
    main()
